# Generated by Django 5.2.10 on 2026-01-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
